### ISSUE TITLE
List (and install) indirect dependencies?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-bundler#1]
D3 modules can have dependencies that may not exist at the top level, so d3-bundler should probably generate an appropriate error if it can’t find that dependency.

For example, say you import the d3-transition module, and maybe that module depends on d3-ease or d3-interpolate. You may not export anything from d3-ease or d3-interpolate at the top level, so you might not realize you need to install those modules, too.

Another way we could fix this would be to give d3-bundler an install command, so that it runs `npm install` for you with the appropriate expanded dependencies. But you’re still going to want to save those dependencies in your package.json and have control over the version numbers, so I’m not sure I want to duplicate any NPM functionality.

**Comment by mbostock** [comment]
Related: we might need to think about versioning constraints on dependencies. Like what if two modules depend on conflicting versions? Since everything must exist at the top level (unless we want to allow code duplication), this probably should generate an error. But, it might still be nice to observe modules’ version constraints as defined in the package.json.

**Comment by curran** [comment]
JSPM <http://jspm.io/> has a compelling solution for package-level
dependency management that handles conflicting versions, and also does
installation, loading, and bundling of transitive dependencies. JSPM augments
package.json with a "jspm" property
<https://github.com/curran/jspm-mocha-example/blob/gh-pages/package.json>,
and installs dependencies in jspm_packages when you run "jspm
install". Guy Bedford, author of JSPM, discusses the multi-version issues
in his video Package Management for ES6 Modules (30:07)
<https://www.youtube.com/watch?v=szJjsduHBQQ>.

I'm not sure if you want to adopt JSPM, the Rollup solution you have so far
is really cool, but food for thought. It might be possible to use JSPM for
package management only, and Rollup for bundling, I'm not sure.

Here's an example project I made while evaluating JSPM
<https://github.com/curran/jspm-mocha-example/tree/master> that might be of
interest.

All the best,
Curran

**Comment by mbostock** [comment]
This has been fixed in d3/d3-scale#3 and npm 3+: the dependent modules are installed at the top-level of node_modules and discovered via rollup-plugin-npm.
