### ISSUE TITLE
Expose functionality via Node module

### ISSUE THREAD

**Issue by curran** [d3/d3-bundler#5]
I am taking a stab at the custom D3 bundling user interface that you have described. https://github.com/curran/d3-bundler-ui

I found that the only way to invoke d3-bundler is via the command line interface. This is [working](https://github.com/curran/d3-bundler-ui/blob/66acc4074d4b87747d171767a1befcb3915e8451/index.js#L54), but it would be nicer if d3-bundler were exposed as a Node module.

I'm imagining an API that looks something like this:

```javascript
var d3Bundler = require("d3-bundler");

var indexJS = [
  "import { select } from \"d3-selection\";",
  "import { event } from \"d3-selection\";",
  "import { transition } from \"d3-transition\";",
  "",
  "export default {",
  "  select: select,",
  "  get event() { return event; },",
  "  transition: transition",
  "};",
].join("\n")

d3Bundler(indexJS, function (err, bundleJS){
  // Hooray! The bundle was created without a temporary file or child process.
});
```

It seems like this should be fairly straightforward, involving the addition of a `main` field in `package.json`, and decoupling the command line parsing logic from the bundling logic.

**Comment by mbostock** [comment]
I don’t think this is necessary now that d3-bundler is just a trivial wrapper on top of rollup and rollup-plugin-npm: you can just copy the bits on [bin/d3-bundler](https://github.com/d3/d3-bundler/blob/master/bin/d3-bundler) you need and invoke it that way.

**Comment by curran** [comment]
Sounds good, thanks for the update!

**Comment by mbostock** [comment]
No problem. I’m trying to make d3-bundler disappear entirely. :stuck_out_tongue_winking_eye:
