### ISSUE TITLE
How to get just a geo projection?

### ISSUE THREAD

**Issue by callumlocke** [d3/d3-bundler#6]
I've got a project where I'm using d3 only to make a projection function like this:

```js
var projection = d3.geo.mercator().scale(s).translate(t);
```

Is there some way I can use d3-bundler to get a tiny version of d3 just for this purpose? I can't see which module I would use. There's d3-geo-projection, but I don't think this is the right thing?

**Comment by mbostock** [comment]
Sorry, but d3-geo-projection hasn’t been re-written to use the new Rollup-based bundling yet. That will come eventually, but it’s not here yet.
